# SPDX-License-Identifier: GPL-2.0-only
obj-$(CONFIG_HYGON_DCU_VFIO_PCI) += hydcu-vfio-pci.o
hydcu-vfio-pci-y := hydcu_vfio_pci.o hydcu_fixup_header.o hydcu_pci_speed.o hydcu_dpc_aer_mgr.o hydcu_comm.o hydcu_misc.o
