{
	"rich_container:  true expected_attach_type(cpu)",
	.insns = {
		BPF_MOV64_IMM(BPF_REG_0, 0),
		BPF_EXIT_INSN(),
	},
	.prog_type = BPF_PROG_TYPE_CGROUP_RICH_CONTAINER,
	.expected_attach_type = BPF_CGROUP_RICH_CONTAINER_CPU,
	.result = ACCEPT,
},
{
	"rich_container: true expected_attach_type(mem)",
	.insns = {
		BPF_MOV64_IMM(BPF_REG_0, 0),
		BPF_EXIT_INSN(),
	},
	.prog_type = BPF_PROG_TYPE_CGROUP_RICH_CONTAINER,
	.expected_attach_type = BPF_CGROUP_RICH_CONTAINER_MEM,
	.result = ACCEPT,
},
{
	"rich_container: invalid ctx access(cpu) 1",
	.insns = {
		BPF_LDX_MEM(BPF_DW, BPF_REG_0, BPF_REG_1,
			    CONFIG_NR_CPUS / 8),
		BPF_MOV64_IMM(BPF_REG_0, 0),
		BPF_EXIT_INSN(),
	},
	.prog_type = BPF_PROG_TYPE_CGROUP_RICH_CONTAINER,
	.expected_attach_type = BPF_CGROUP_RICH_CONTAINER_CPU,
	.result = REJECT,
	.errstr = "invalid bpf_context access",
},
{
	"rich_container:  invalid ctx access(cpu) 2",
	.insns = {
		BPF_LDX_MEM(BPF_DW, BPF_REG_0, BPF_REG_1, 10000),
		BPF_MOV64_IMM(BPF_REG_0, 0),
		BPF_EXIT_INSN(),
	},
	.prog_type = BPF_PROG_TYPE_CGROUP_RICH_CONTAINER,
	.expected_attach_type = BPF_CGROUP_RICH_CONTAINER_CPU,
	.result = REJECT,
	.errstr = "invalid bpf_context access",
},
{
	"rich_container: invalid ctx access(mem) 1",
	.insns = {
		BPF_LDX_MEM(BPF_DW, BPF_REG_0, BPF_REG_1, 0),
		BPF_MOV64_IMM(BPF_REG_0, 0),
		BPF_EXIT_INSN(),
	},
	.prog_type = BPF_PROG_TYPE_CGROUP_RICH_CONTAINER,
	.expected_attach_type = BPF_CGROUP_RICH_CONTAINER_MEM,
	.result = REJECT,
	.errstr = "invalid bpf_context access",
},
{
	"rich_container: invalid ctx access(mem) 2",
	.insns = {
		BPF_LDX_MEM(BPF_DW, BPF_REG_0, BPF_REG_1, 10000),
		BPF_MOV64_IMM(BPF_REG_0, 0),
		BPF_EXIT_INSN(),
	},
	.prog_type = BPF_PROG_TYPE_CGROUP_RICH_CONTAINER,
	.expected_attach_type = BPF_CGROUP_RICH_CONTAINER_MEM,
	.result = REJECT,
	.errstr = "invalid bpf_context access",
},
{
	"rich_container: invalid return value",
	.insns = {
		BPF_MOV64_IMM(BPF_REG_0, 2),
		BPF_EXIT_INSN(),
	},
	.prog_type = BPF_PROG_TYPE_CGROUP_RICH_CONTAINER,
	.expected_attach_type = BPF_CGROUP_RICH_CONTAINER_CPU,
	.result = REJECT,
	.errstr = "At program exit the register R0",
},
